# topDir: "F:/Downloads/misc/"
topDir: "X:/downloads/misc/"
cjPath: "W:\\Users\\Nick\\AppData\\Local\\JDownloader 2.0\\folderwatch\\"
cjPath1: "\\\\10.0.0.101\\appdata\\JDownloader2\\folderwatch"
cjPath2: "\\\\10.0.0.101\\appdata\\JDownloader3\\folderwatch"
cjPath3: "\\\\10.0.0.101\\appdata\\JDownloader4\\folderwatch"
pydlpAddress: "10.0.0.101"
pydlpPort: "5353"
pydlp2Port: "5354"